# Generated by Django 3.2.23 on 2024-04-22 09:34

from django.db import migrations


class Migration(migrations.Migration):
    """
    Represents a migration in Django.
    """

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_on"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_on"]},
        ),
    ]
