# Generated by Django 3.2.23 on 2024-04-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20240424_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
