# Generated by Django 3.2.23 on 2024-04-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Initial migration for the About model in the Django application.
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
            ],
        ),
    ]
