# Generated by Django 3.2.23 on 2024-04-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration for creating the 'CollaborateRequest' 
    model in the database.
    """

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("read", models.BooleanField(default=False)),
            ],
        ),
    ]
